unstable_features = true
indent_style = "Block"
use_small_heuristics = "Max"
binop_separator = "Front"
combine_control_expr = false
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
fn_args_density = "Tall"
brace_style = "PreferSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 100
fn_single_line = false
where_single_line = true
force_explicit_abi = true
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
max_width = 160
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
report_todo = "Never"
report_fixme = "Always"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 40
spaces_around_ranges = false
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = false
wrap_comments = false
match_arm_blocks = true
overflow_delimited_expr = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
hide_parse_errors = false
color = "Auto"
edition = "2018"
normalize_doc_attributes = false
inline_attribute_width = 0
